[package]
name = "ow2-tournament-be"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.29"
pretty_env_logger = "0.5.0"
tokio = { version = "1.49.0", features = ["full"] }
actix-web = "4.13.0"
config = "0.15.19"
dotenv = "0.15.0"
sqlx = { version = "0.8.6", features = [
    "sqlite",
    "chrono",
    "runtime-tokio",
    "json",
] }
reqwest = { version = "0.13.2", default-features = false, features = [
    "json",
    "form",
    "query",
    "native-tls-vendored",
] }
openssl = { version = "0.10.75", features = ["vendored"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_with = { version = "3.16.1", features = ["chrono"] }
thiserror = "2.0.18"
rand = "0.10.0"
futures-util = "0.3.32"
serde_urlencoded = "0.7.1"
serde_qs = { version = "1.0.0", features = ["actix4"] }
strum = "0.27.2"
strum_macros = "0.27.2"
jsonwebtoken = { version = "10.3.0", features = ["rust_crypto"] }
base64 = "0.22.1"
chrono = "0.4.43"
async-trait = "0.1.89"
actix-multipart = "0.7.2"
ulid = { version = "1.2.1", features = ["serde"] }
tokio-cron-scheduler = { version = "0.15.1", features = ["signal"] }
mime_guess = "2.0.5"
csv = "1.4.0"
enum_dispatch = "0.3.13"
tracing = "0.1.44"

[dev-dependencies]
tempfile = "3.25.0"
httpmock = "0.8.3"
