CREATE TABLE match_player_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  match_id INTEGER,
  round INTEGER,
  team_id INTEGER,
  player_id INTEGER,
  hero_id INTEGER,
  time TIME,
  event TEXT,
  data JSON,

  FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE NO ACTION ON UPDATE NO ACTION
  FOREIGN KEY (hero_id) REFERENCES heroes(id) ON DELETE NO ACTION ON UPDATE NO ACTION
);
