CREATE TABLE match_player_statistics (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  match_id INTEGER,
  round INTEGER,
  team_id INTEGER,
  player_id INTEGER,
  hero_id INTEGER,

  eliminations INTEGER,
  final_blows INTEGER,
  deaths INTEGER,
  all_damage FLOAT,
  barrier_damage FLOAT,
  hero_damage FLOAT,
  healing_dealt FLOAT,
  healing_received FLOAT,
  self_healing FLOAT,
  damage_taken FLOAT,
  defensive_assists INTEGER,
  offensive_assists INTEGER,
  ultimates_earned INTEGER,
  ultimates_used INTEGER,
  multikill_best INTEGER,
  multikills INTEGER,
  solo_kills INTEGER,
  objective_kills INTEGER,
  environmental_kills INTEGER,
  environmental_deaths INTEGER,
  critical_hits INTEGER,
  critical_hit_accuracy INTEGER,
  scoped_accuracy INTEGER,
  scoped_critical_hit_accuracy INTEGER,
  scoped_critical_hit_kills INTEGER,
  shots_fired INTEGER,
  shots_hit INTEGER,
  shots_missed INTEGER,
  scoped_shots_fired INTEGER,
  scoped_shots_hit INTEGER,
  weapon_accuracy INTEGER,
  hero_time_played FLOAT,

  FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE NO ACTION ON UPDATE NO ACTION
  FOREIGN KEY (hero_id) REFERENCES heroes(id) ON DELETE NO ACTION ON UPDATE NO ACTION
);
