CREATE TABLE game_maps (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  map_id INTEGER NOT NULL,
  mode_id INTEGER NOT NULL,
  FOREIGN KEY (map_id) REFERENCES maps(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (mode_id) REFERENCES modes(id) ON DELETE NO ACTION ON UPDATE NO ACTION
);
