INSERT INTO heroes (name) VALUES
  ('Vendetta'),
  ('Ana'),
  ('Ashe'),
  ('Baptiste'),
  ('Bastion'),
  ('Brigitte'),
  ('Cassidy'),
  ('D.Va'),
  ('Doomfist'),
  ('Echo'),
  ('Freja'),
  ('Genji'),
  ('Hanzo'),
  ('Hazard'),
  ('Illari'),
  ('Junker Queen'),
  ('Junkrat'),
  ('Juno'),
  ('Kiriko'),
  ('Lifeweaver'),
  ('Lúcio'),
  ('Mauga'),
  ('Mei'),
  ('Mercy'),
  ('Moira'),
  ('Orisa'),
  ('Pharah'),
  ('Ramattra'),
  ('Reaper'),
  ('Reinhardt'),
  ('Roadhog'),
  ('Sigma'),
  ('Sojourn'),
  ('Soldier: 76'),
  ('Sombra'),
  ('Symmetra'),
  ('Torbjörn'),
  ('Tracer'),
  ('Venture'),
  ('Widowmaker'),
  ('Winston'),
  ('Wrecking Ball'),
  ('Wuyang'),
  ('Zarya'),
  ('Zenyatta');

INSERT INTO heroes_localization (hero_id, name, lang) VALUES
  ((SELECT id FROM heroes WHERE name='Vendetta'),'Vendetta','en'),
  ((SELECT id FROM heroes WHERE name='Ana'),'Ana','en'),
  ((SELECT id FROM heroes WHERE name='Ashe'),'Ashe','en'),
  ((SELECT id FROM heroes WHERE name='Baptiste'),'Baptiste','en'),
  ((SELECT id FROM heroes WHERE name='Bastion'),'Bastion','en'),
  ((SELECT id FROM heroes WHERE name='Brigitte'),'Brigitte','en'),
  ((SELECT id FROM heroes WHERE name='Cassidy'),'Cassidy','en'),
  ((SELECT id FROM heroes WHERE name='D.Va'),'D.Va','en'),
  ((SELECT id FROM heroes WHERE name='Doomfist'),'Doomfist','en'),
  ((SELECT id FROM heroes WHERE name='Echo'),'Echo','en'),
  ((SELECT id FROM heroes WHERE name='Freja'),'Freja','en'),
  ((SELECT id FROM heroes WHERE name='Genji'),'Genji','en'),
  ((SELECT id FROM heroes WHERE name='Hanzo'),'Hanzo','en'),
  ((SELECT id FROM heroes WHERE name='Hazard'),'Hazard','en'),
  ((SELECT id FROM heroes WHERE name='Illari'),'Illari','en'),
  ((SELECT id FROM heroes WHERE name='Junker Queen'),'Junker Queen','en'),
  ((SELECT id FROM heroes WHERE name='Junkrat'),'Junkrat','en'),
  ((SELECT id FROM heroes WHERE name='Juno'),'Juno','en'),
  ((SELECT id FROM heroes WHERE name='Kiriko'),'Kiriko','en'),
  ((SELECT id FROM heroes WHERE name='Lifeweaver'),'Lifeweaver','en'),
  ((SELECT id FROM heroes WHERE name='Lúcio'),'Lúcio','en'),
  ((SELECT id FROM heroes WHERE name='Mauga'),'Mauga','en'),
  ((SELECT id FROM heroes WHERE name='Mei'),'Mei','en'),
  ((SELECT id FROM heroes WHERE name='Mercy'),'Mercy','en'),
  ((SELECT id FROM heroes WHERE name='Moira'),'Moira','en'),
  ((SELECT id FROM heroes WHERE name='Orisa'),'Orisa','en'),
  ((SELECT id FROM heroes WHERE name='Pharah'),'Pharah','en'),
  ((SELECT id FROM heroes WHERE name='Ramattra'),'Ramattra','en'),
  ((SELECT id FROM heroes WHERE name='Reaper'),'Reaper','en'),
  ((SELECT id FROM heroes WHERE name='Reinhardt'),'Reinhardt','en'),
  ((SELECT id FROM heroes WHERE name='Roadhog'),'Roadhog','en'),
  ((SELECT id FROM heroes WHERE name='Sigma'),'Sigma','en'),
  ((SELECT id FROM heroes WHERE name='Sojourn'),'Sojourn','en'),
  ((SELECT id FROM heroes WHERE name='Soldier: 76'),'Soldier: 76','en'),
  ((SELECT id FROM heroes WHERE name='Sombra'),'Sombra','en'),
  ((SELECT id FROM heroes WHERE name='Symmetra'),'Symmetra','en'),
  ((SELECT id FROM heroes WHERE name='Torbjörn'),'Torbjörn','en'),
  ((SELECT id FROM heroes WHERE name='Tracer'),'Tracer','en'),
  ((SELECT id FROM heroes WHERE name='Venture'),'Venture','en'),
  ((SELECT id FROM heroes WHERE name='Widowmaker'),'Widowmaker','en'),
  ((SELECT id FROM heroes WHERE name='Winston'),'Winston','en'),
  ((SELECT id FROM heroes WHERE name='Wrecking Ball'),'Wrecking Ball','en'),
  ((SELECT id FROM heroes WHERE name='Wuyang'),'Wuyang','en'),
  ((SELECT id FROM heroes WHERE name='Zarya'),'Zarya','en'),
  ((SELECT id FROM heroes WHERE name='Zenyatta'),'Zenyatta','en');

INSERT INTO heroes_localization (hero_id, name, lang) VALUES
  ((SELECT id FROM heroes WHERE name='Vendetta'),'Вендетта','ru'),
  ((SELECT id FROM heroes WHERE name='Ana'),'Ана','ru'),
  ((SELECT id FROM heroes WHERE name='Ashe'),'Эш','ru'),
  ((SELECT id FROM heroes WHERE name='Baptiste'),'Батист','ru'),
  ((SELECT id FROM heroes WHERE name='Bastion'),'Бастион','ru'),
  ((SELECT id FROM heroes WHERE name='Brigitte'),'Бригитта','ru'),
  ((SELECT id FROM heroes WHERE name='Cassidy'),'Кэссиди','ru'),
  ((SELECT id FROM heroes WHERE name='D.Va'),'D.Va','ru'),
  ((SELECT id FROM heroes WHERE name='Doomfist'),'Кулак Смерти','ru'),
  ((SELECT id FROM heroes WHERE name='Echo'),'Эхо','ru'),
  ((SELECT id FROM heroes WHERE name='Freja'),'Фрейя','ru'),
  ((SELECT id FROM heroes WHERE name='Genji'),'Гэндзи','ru'),
  ((SELECT id FROM heroes WHERE name='Hanzo'),'Хандзо','ru'),
  ((SELECT id FROM heroes WHERE name='Hazard'),'Азарт','ru'),
  ((SELECT id FROM heroes WHERE name='Illari'),'Иллари','ru'),
  ((SELECT id FROM heroes WHERE name='Junker Queen'),'Королева Стервятников','ru'),
  ((SELECT id FROM heroes WHERE name='Junkrat'),'Крысавчик','ru'),
  ((SELECT id FROM heroes WHERE name='Juno'),'Юнона','ru'),
  ((SELECT id FROM heroes WHERE name='Kiriko'),'Кирико','ru'),
  ((SELECT id FROM heroes WHERE name='Lifeweaver'),'Ткач Жизни','ru'),
  ((SELECT id FROM heroes WHERE name='Lúcio'),'Лусио','ru'),
  ((SELECT id FROM heroes WHERE name='Mauga'),'Мауга','ru'),
  ((SELECT id FROM heroes WHERE name='Mei'),'Мэй','ru'),
  ((SELECT id FROM heroes WHERE name='Mercy'),'Ангел','ru'),
  ((SELECT id FROM heroes WHERE name='Moira'),'Мойра','ru'),
  ((SELECT id FROM heroes WHERE name='Orisa'),'Ориса','ru'),
  ((SELECT id FROM heroes WHERE name='Pharah'),'Фарра','ru'),
  ((SELECT id FROM heroes WHERE name='Ramattra'),'Раматтра','ru'),
  ((SELECT id FROM heroes WHERE name='Reaper'),'Жнец','ru'),
  ((SELECT id FROM heroes WHERE name='Reinhardt'),'Райнхардт','ru'),
  ((SELECT id FROM heroes WHERE name='Roadhog'),'Турбосвин','ru'),
  ((SELECT id FROM heroes WHERE name='Sigma'),'Сигма','ru'),
  ((SELECT id FROM heroes WHERE name='Sojourn'),'Соджорн','ru'),
  ((SELECT id FROM heroes WHERE name='Soldier: 76'),'Солдат-76','ru'),
  ((SELECT id FROM heroes WHERE name='Sombra'),'Сомбра','ru'),
  ((SELECT id FROM heroes WHERE name='Symmetra'),'Симметра','ru'),
  ((SELECT id FROM heroes WHERE name='Torbjörn'),'Торбьорн','ru'),
  ((SELECT id FROM heroes WHERE name='Tracer'),'Трейсер','ru'),
  ((SELECT id FROM heroes WHERE name='Venture'),'Авентюра','ru'),
  ((SELECT id FROM heroes WHERE name='Widowmaker'),'Роковая Вдова','ru'),
  ((SELECT id FROM heroes WHERE name='Winston'),'Уинстон','ru'),
  ((SELECT id FROM heroes WHERE name='Wrecking Ball'),'Таран','ru'),
  ((SELECT id FROM heroes WHERE name='Wuyang'),'У Ян','ru'),
  ((SELECT id FROM heroes WHERE name='Zarya'),'Заря','ru'),
  ((SELECT id FROM heroes WHERE name='Zenyatta'),'Дзенъятта','ru');
