CREATE TABLE teams (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  modified_at DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  deleted_at DATETIME
);
