CREATE TABLE divisions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tournament_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  tier INTEGER NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  modified_at DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),

  UNIQUE (tournament_id, name),
  FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE NO ACTION ON UPDATE NO ACTION
);
