DROP TABLE match_player_statistics;

CREATE TABLE match_player_statistics (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  match_map_id INTEGER NOT NULL,
  round INTEGER,
  player_id INTEGER,
  hero_id INTEGER,

  eliminations INTEGER,
  final_blows INTEGER,
  deaths INTEGER,
  all_damage REAL,
  barrier_damage REAL,
  hero_damage REAL,
  healing_dealt REAL,
  healing_received REAL,
  self_healing REAL,
  damage_taken REAL,
  damage_blocked REAL,
  defensive_assists INTEGER,
  offensive_assists INTEGER,
  ultimates_earned INTEGER,
  ultimates_used INTEGER,
  multikill_best INTEGER,
  multikills INTEGER,
  solo_kills INTEGER,
  objective_kills INTEGER,
  environmental_kills INTEGER,
  environmental_deaths INTEGER,
  critical_hits INTEGER,
  critical_hit_accuracy REAL,
  scoped_accuracy REAL,
  scoped_critical_hit_accuracy REAL,
  scoped_critical_hit_kills INTEGER,
  shots_fired INTEGER,
  shots_hit INTEGER,
  shots_missed INTEGER,
  scoped_shots_fired INTEGER,
  scoped_shots_hit INTEGER,
  weapon_accuracy REAL,
  hero_time_played REAL,

  UNIQUE (match_map_id, round, player_id, hero_id),
  FOREIGN KEY (match_map_id) REFERENCES match_maps(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (hero_id) REFERENCES heroes(id) ON DELETE NO ACTION ON UPDATE NO ACTION
);
