CREATE TABLE tournaments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  deleted_at DATETIME,
  started_at DATETIME,
  finished_at DATETIME,
  name TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  modified_at DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
